### ISSUE TITLE
Bad call to memcpy when source has carriage returns

### ISSUE THREAD

**Issue by tskeith** [ThePortlandGroup/f18#108]
If you run `valgrind f18 -fparse-only a.f90` where `a.f90` contains carriage returns, it reports:
```
Source and destination overlap in memcpy(0x4023000, 0x4023000, 3)
   at 0x4C2E04C: memcpy@@GLIBC_2.14 (vg_replace_strmem.c:1022)
   by 0x8B7CE8: Fortran::parser::RemoveCarriageReturns(char*, unsigned long) (source.cc:93)
```

It seems to work okay, but the behavior of `memcpy` is undefined when the source and destination overlap. And it would be nice to be able to run cleanly with valgrind.

**Comment by klausler** [comment]
Fixed in PR #111
