### ISSUE TITLE
Error recovery: executable construct in module

### ISSUE THREAD

**Issue by tskeith** [ThePortlandGroup/f18#98]
For this example:
```
module m
  i = 1
end
```
the parse reports this error:
```
a.f90:1:8: error: expected '('
  module m
         ^
a.f90:1:1: in the context: statement function definition
  module m
  ^
```

This could be especially confusing because even with declarations before the assignment the error seems to be the same. So the error message can be pointing a long way from where the error occurs.

**Comment by klausler** [comment]
Fixed with pull request #103
